name: Build LaTeX document
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: thesis.tex
          args: -xelatex -file-line-error -interaction=nonstopmode
          working_directory: paper/
      - name: Upload To Artifact
        uses: actions/upload-artifact@v1
        with:
            name: paper
            path: paper/thesis.pdf